var nombre = 'Jeison';
var apellido = 'Cerpa';
var apellido2 = 'Osorio';
var nombre1 = document.getElementById("nombre");
var apellido11= document.getElementById("apellido");
var apellido22 = document.getElementById("apellido2");
nombre1.innerHTML = `El nombre es: ${nombre}`;
apellido11.innerHTML = `El primer apellido es: ${apellido}`;
apellido22.innerHTML = `El segundo apellido es: ${apellido2}`;